library(tRNA)

context("tRNA structure seqs")
test_that("tRNA structure seqs:",{
  data("gr", package = "tRNA", envir = environment())
  tRNA <- gr
  tRNA <- tRNA[1]
  strList <- gettRNABasePairing(tRNA)
  actual <- tRNA:::.getAcceptorStem(tRNA, strList)
  expect_named(actual, c("prime5","prime3"))
  expect_named(actual[[1]], c("start","end"))
  expect_named(actual[[2]], c("start","end"))
  expect_equal(actual[[2]], list(start = 64,end = 70))
  actual <- tRNA:::.getDiscriminator(tRNA, strList)
  expect_equal(actual, 71)
  actual <- tRNA:::.getDprime5(tRNA, strList)
  expect_named(actual, c("start","end"))
  expect_equal(actual, list(start = 8,end = 9))
  actual <- tRNA:::.getDstem(tRNA, strList)
  expect_named(actual, c("prime5","prime3"))
  expect_named(actual[[1]], c("start","end"))
  expect_named(actual[[2]], c("start","end"))
  expect_equal(actual[[2]], list(start = 21,end = 24))
  actual <- tRNA:::.getDloop(tRNA, strList)
  expect_named(actual, c("start","end"))
  expect_equal(actual, list(start = 14,end = 20))
  actual <- tRNA:::.getDprime3(tRNA, strList)
  expect_named(actual, c("start","end"))
  expect_equal(actual, list(start = 25,end = 25))
  actual <- tRNA:::.getAnticodonStem(tRNA, strList)
  expect_named(actual, c("prime5","prime3"))
  expect_named(actual[[1]], c("start","end"))
  expect_named(actual[[2]], c("start","end"))
  expect_equal(actual[[2]], list(start = 38,end = 42))
  actual <- tRNA:::.getAnticodonLoop(tRNA, strList)
  expect_named(actual, c("start","end"))
  expect_equal(actual, list(start = 31,end = 37))
  actual <- tRNA:::.getVariableLoop(tRNA, strList)
  expect_named(actual, c("start","end"))
  expect_equal(actual, list(start = 43,end = 46))
  actual <- tRNA:::.getTstem(tRNA, strList)
  expect_named(actual, c("prime5","prime3"))
  expect_named(actual[[1]], c("start","end"))
  expect_named(actual[[2]], c("start","end"))
  expect_equal(actual[[2]], list(start = 59,end = 63))
  actual <- tRNA:::.getTloop(tRNA, strList)
  expect_named(actual, c("start","end"))
  expect_equal(actual, list(start = 52,end = 58))
  # check that the sequences are unharmed by chopping it into pieces
  tRNA <- gr
  seqs <- gettRNAstructureSeqs(gr,
                               joinCompletely = TRUE,
                               joinFeatures = FALSE)
  seqsChars <- gsub("-","",as.character(seqs))
  expect_equal(seqsChars,as.character(tRNA$tRNA_seq))
  expect_named(S4Vectors::metadata(seqs),"tRNA_structures")
})
